version = 1

[[analyzers]]
name = "csharp"
enabled = true

[analyzers.meta]
language_version = "11.0"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true