name: Python_included
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
        include-prerelease: true

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: false
        cache: 'pip'
        cache-dependency-path: '\a\QuanTAlib\QuanTAlib\Tests\requirements.txt'

    - name: Install dependencies
      run: pip install -r '\a\QuanTAlib\QuanTAlib\Tests\requirements.txt'

    - name: path
      run: '$env:path -split ";"'



